apiVersion: v1
kind: Pod
metadata:
  name: kube-controller-manager
  namespace: kube-system
spec:
  containers:
    - name: kube-controller-manager
      volumeMounts:
        - mountPath: /usr/libexec/kubernetes/kubelet-plugins/volume/exec
          $patch: delete
  volumes:
    - name: flexvolume-dir
      $patch: delete
